<a href="https://www.kaggle.com/code/chandunarisetti/student-marks-prediction?scriptVersionId=224959953" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/student-marks-dataset/Student_Marks.csv

# import the packages

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# loading the dataset

In [3]:
data = pd.read_csv("/kaggle/input/student-marks-dataset/Student_Marks.csv")

In [4]:
data.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [5]:
data.tail()

    number_courses  time_study   Marks
95               6       3.561  19.128
96               3       0.301   5.609
97               4       7.163  41.444
98               7       0.309  12.027
99               3       6.335  32.357

In [6]:
data.isnull().sum()

number_courses    0
time_study        0
Marks             0
dtype: int64

In [7]:
data["number_courses"].value_counts()

number_courses
3    22
4    21
6    16
8    16
7    15
5    10
Name: count, dtype: int64

## visualization

In [8]:
figure = px.scatter(data_frame=data, x="number_courses",
                   y="Marks", size = "time_study", title=
                   "number of courses and marks scored")

In [9]:
figure.show()

In [10]:
fig = px.scatter(data_frame=data, x="time_study", 
                y="Marks", size="number_courses", 
                title = "time spent and marks scored",
                trendline="ols")

In [11]:
fig.show()

# finding the correlation

In [12]:
correlation=data.corr()
print(correlation["Marks"].sort_values(ascending=False))

Marks             1.000000
time_study        0.942254
number_courses    0.417335
Name: Marks, dtype: float64

# seperating the target and features

In [13]:
x = np.array(data[["time_study", "number_courses" ]])
y = np.array(data["Marks"])

# splitting the data into train and test sets

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.2, random_state=42)

# initialization of model

In [15]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [16]:
model.score(x_test, y_test)

0.9459936100591212

In [17]:
# Features = [["time_study", "number_courses"]]
features = np.array([[4.508, 8]])
model.predict(features)

array([31.66513426])